/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.1.0

Source Server         : fk_caibo
Source Server Version : 110200
Source Host           : 172.20.16.194:1521
Source Schema         : LOTTERYTIE

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-07-06 16:33:05
*/


-- ----------------------------
-- Table structure for CHITCHAT_DEPT
-- ----------------------------
DROP TABLE "LOTTERYTIE"."CHITCHAT_DEPT";
CREATE TABLE "LOTTERYTIE"."CHITCHAT_DEPT" (
"ID" NUMBER(19) NOT NULL ,
"NAME" VARCHAR2(255 BYTE) NULL ,
"CODE" VARCHAR2(255 BYTE) NULL ,
"PARENT_ID" NUMBER(19) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CHITCHAT_DEPT
-- ----------------------------
INSERT INTO "LOTTERYTIE"."CHITCHAT_DEPT" VALUES ('14', '技术部', 'jsb', '13');
INSERT INTO "LOTTERYTIE"."CHITCHAT_DEPT" VALUES ('13', '疯狂体育', 'fkty', '0');

-- ----------------------------
-- Table structure for CHITCHAT_RESOURCES
-- ----------------------------
DROP TABLE "LOTTERYTIE"."CHITCHAT_RESOURCES";
CREATE TABLE "LOTTERYTIE"."CHITCHAT_RESOURCES" (
"ID" NUMBER(19) NOT NULL ,
"NAME" VARCHAR2(255 BYTE) NULL ,
"RESURL" VARCHAR2(255 BYTE) NULL ,
"TYPE" NUMBER(19) NULL ,
"PARENTID" NUMBER(19) NULL ,
"SORT" NUMBER(19) NULL ,
"ICONCLS" VARCHAR2(100 BYTE) NULL ,
"BUT_FUN" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CHITCHAT_RESOURCES
-- ----------------------------
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('1', '系统设置', null, '1', '0', '10', null, null);
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('2', '用户管理', '/page/users', '1', '1', '20', null, null);
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('3', '角色管理', '/page/roles', '1', '1', '30', null, null);
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('4', '菜单管理', '/page/resources', '1', '1', '40', null, null);
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('5', '添加用户', '/users/add', '2', '2', '1', 'icon-add-new', 'add()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('6', '删除用户', '/users/delete', '2', '2', '2', 'icon-remove-new', 'remove()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('7', '添加角色', '/roles/add', '2', '3', '1', 'icon-add-new', 'add()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('8', '删除角色', '/roles/delete', '2', '3', '2', 'icon-remove-new', 'remove()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('9', '添加资源', '/resources/add', '2', '4', '1', 'icon-add-new', 'add()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('10', '删除资源', '/resources/delete', '2', '4', '2', 'icon-remove-new', 'remove()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('13', '分配权限', '/roles/saveRoleResources', '2', '3', '4', null, 'saveRoleResources()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('14', '修改资源', '/resources/edit', '2', '4', '3', 'icon-edit-new', 'edit()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('15', '修改角色', '/roles/edit', '2', '3', '3', 'icon-edit-new', 'edit()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('16', '添加部门', '/dept/add', '2', '55', '1', 'icon-add-new', 'add()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('17', '删除部门', '/dept/delete', '2', '55', '2', 'icon-remove-new', 'remove()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('18', '修改部门', '/dept/edit', '2', '55', '3', 'icon-edit-new', 'edit()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('19', '资源管理', '/page/buttons', '1', '1', '50', null, null);
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('55', '部门管理', '/page/depts', '1', '1', '10', null, null);
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('56', '修改用户', '/users/edit', '2', '2', '3', 'icon-edit-new', 'edit()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('57', '停用', '/users/off', '2', '2', '4', 'icon-off-new', 'off()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('58', '启用', '/users/on', '2', '2', '5', 'icon-on-new', 'on()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('59', '添加按钮', '/buttons/add', '2', '19', '1', 'icon-add-new', 'add()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('60', '修改按钮', '/buttons/edit', '2', '19', '2', 'icon-edit-new', 'edit()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('61', '删除按钮', '/buttons/delete', '2', '19', '3', 'icon-remove-new', 'remove()');
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('75', '每日数据统计', null, '1', '0', '80', null, null);
INSERT INTO "LOTTERYTIE"."CHITCHAT_RESOURCES" VALUES ('85', '每日数据一对多汇总', '/page/dailyData', '1', '75', '10', null, null);

-- ----------------------------
-- Table structure for CHITCHAT_ROLE
-- ----------------------------
DROP TABLE "LOTTERYTIE"."CHITCHAT_ROLE";
CREATE TABLE "LOTTERYTIE"."CHITCHAT_ROLE" (
"ID" NUMBER(11) NOT NULL ,
"ROLEDESC" VARCHAR2(255 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CHITCHAT_ROLE
-- ----------------------------
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE" VALUES ('1', '超级管理员');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE" VALUES ('3', '管理员');

-- ----------------------------
-- Table structure for CHITCHAT_ROLE_RESOURCES
-- ----------------------------
DROP TABLE "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES";
CREATE TABLE "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" (
"ROLEID" NUMBER(11) NOT NULL ,
"RESOURCESID" NUMBER(11) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CHITCHAT_ROLE_RESOURCES
-- ----------------------------
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '1');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '2');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '3');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '4');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '5');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '6');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '7');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '8');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '9');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '10');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '13');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '14');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '15');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '16');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '17');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '18');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '19');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '55');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '56');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '57');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '58');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '59');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '60');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '61');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '65');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '66');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '67');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '68');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '69');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '70');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '72');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '73');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '74');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '75');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '85');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('1', '86');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '1');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '2');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '3');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '4');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '5');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '6');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '7');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '8');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '9');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '10');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '13');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '14');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '15');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '16');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '17');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '18');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '19');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '55');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '56');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '57');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '58');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '59');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '60');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '61');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '65');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '66');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '67');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '68');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '69');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '70');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '72');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '73');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '74');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '75');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '85');
INSERT INTO "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" VALUES ('3', '86');

-- ----------------------------
-- Table structure for CHITCHAT_USER
-- ----------------------------
DROP TABLE "LOTTERYTIE"."CHITCHAT_USER";
CREATE TABLE "LOTTERYTIE"."CHITCHAT_USER" (
"ID" NUMBER(11) NOT NULL ,
"USERNAME" VARCHAR2(33 BYTE) NULL ,
"PASSWORD" VARCHAR2(33 BYTE) NULL ,
"ENABLE" NUMBER(10) DEFAULT '1'  NULL ,
"NAME" VARCHAR2(50 BYTE) NULL ,
"ADDRESS" VARCHAR2(100 BYTE) NULL ,
"MARK" VARCHAR2(255 BYTE) NULL ,
"DEPT_ID" NUMBER(11) NULL ,
"PHONE" VARCHAR2(20 BYTE) NULL ,
"CONTACT_NUMBER" VARCHAR2(20 BYTE) NULL ,
"CONTACT" VARCHAR2(50 BYTE) NULL ,
"STORE" NUMBER(11) NULL ,
"CONTACT_ADDRESS" NUMBER(11) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CHITCHAT_USER
-- ----------------------------
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER" VALUES ('1', 'admin', '928bfd2577490322a6e19b793691467e', '1', '管理员', '北京', '管理员', '5', '15510505500', '15254566709', '张三', '44', '46');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER" VALUES ('105', 'kangting', '5c925d6a1546996019accf8fc9586cb8', '1', '康婷', '望京', null, '14', '13020067870', null, null, null, null);
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER" VALUES ('34', 'nieht', '5786f2c82a003c9b90b251f1198540e4', '1', '技术部', '望京', '就是这么牛逼', '14', '15656358881', null, null, null, null);

-- ----------------------------
-- Table structure for CHITCHAT_USER_ROLE
-- ----------------------------
DROP TABLE "LOTTERYTIE"."CHITCHAT_USER_ROLE";
CREATE TABLE "LOTTERYTIE"."CHITCHAT_USER_ROLE" (
"USERID" NUMBER(11) NULL ,
"ROLEID" NUMBER(11) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CHITCHAT_USER_ROLE
-- ----------------------------
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('4', '9');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('3', '9');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('26', '8');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('27', '9');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('28', '9');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('29', '1');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('30', '1');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('31', '1');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('31', '2');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('31', '3');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('31', '4');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('33', '1');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('1', '1');
INSERT INTO "LOTTERYTIE"."CHITCHAT_USER_ROLE" VALUES ('34', '3');

-- ----------------------------
-- Indexes structure for table CHITCHAT_DEPT
-- ----------------------------

-- ----------------------------
-- Checks structure for table CHITCHAT_DEPT
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_DEPT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "LOTTERYTIE"."CHITCHAT_DEPT" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CHITCHAT_DEPT
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_DEPT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CHITCHAT_RESOURCES
-- ----------------------------

-- ----------------------------
-- Checks structure for table CHITCHAT_RESOURCES
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_RESOURCES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "LOTTERYTIE"."CHITCHAT_RESOURCES" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CHITCHAT_RESOURCES
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_RESOURCES" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CHITCHAT_ROLE
-- ----------------------------

-- ----------------------------
-- Checks structure for table CHITCHAT_ROLE
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "LOTTERYTIE"."CHITCHAT_ROLE" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CHITCHAT_ROLE
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CHITCHAT_ROLE_RESOURCES
-- ----------------------------

-- ----------------------------
-- Checks structure for table CHITCHAT_ROLE_RESOURCES
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" ADD CHECK ("ROLEID" IS NOT NULL);
ALTER TABLE "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" ADD CHECK ("RESOURCESID" IS NOT NULL);
ALTER TABLE "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" ADD CHECK ("ROLEID" IS NOT NULL);
ALTER TABLE "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" ADD CHECK ("RESOURCESID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CHITCHAT_ROLE_RESOURCES
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_ROLE_RESOURCES" ADD PRIMARY KEY ("ROLEID", "RESOURCESID");

-- ----------------------------
-- Indexes structure for table CHITCHAT_USER
-- ----------------------------

-- ----------------------------
-- Checks structure for table CHITCHAT_USER
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_USER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "LOTTERYTIE"."CHITCHAT_USER" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CHITCHAT_USER
-- ----------------------------
ALTER TABLE "LOTTERYTIE"."CHITCHAT_USER" ADD PRIMARY KEY ("ID");
